pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io
import Qt.labs.platform

// DO NOT EDIT THIS FILE; it won't actually change anything and is just used to generate and expose a JSON file to the shell for configuration.
// Edit config.json directly instead.

Singleton {
    id: root
    readonly property string filePath: StandardPaths.standardLocations(StandardPaths.ConfigLocation)[0] + "/quickshell/yosemite/config.json"
    property alias options: configJson
    property bool ready: false
    property int readWriteDelay: 40
    property bool block: false

    function setNestedValue(nestedKey, value) {
        let keys = nestedKey.split(".");
        let obj = root.options;
        let parents = [obj];

        // Traverse and collect parent objects
        for (let i = 0; i < keys.length - 1; ++i) {
            if (!obj[keys[i]] || typeof obj[keys[i]] !== "object") {
                obj[keys[i]] = {};
            }
            obj = obj[keys[i]];
            parents.push(obj);
        }

        // Convert value to correct type using JSON.parse when safe
        let convertedValue = value;
        if (typeof value === "string") {
            let trimmed = value.trim();
            if (trimmed === "true" || trimmed === "false" || !isNaN(Number(trimmed))) {
                try {
                    convertedValue = JSON.parse(trimmed);
                } catch (e) {
                    convertedValue = value;
                }
            }
        }

        obj[keys[keys.length - 1]] = convertedValue;
    }

    Timer {
        id: fileReloadTimer
        interval: root.readWriteDelay
        repeat: false
        onTriggered: {
            configFileView.reload();
        }
    }

    Timer {
        id: fileWriteTimer
        interval: root.readWriteDelay
        repeat: false
        onTriggered: {
            configFileView.writeAdapter();
        }
    }

    FileView {
        id: configFileView
        path: root.filePath
        watchChanges: true
        blockWrites: root.block
        onFileChanged: fileReloadTimer.restart()
        onAdapterUpdated: writeAdapter()
        onLoaded: {
            root.ready = true;
        }
        onLoadFailed: error => {
            if (error == FileViewError.FileNotFound) {
                console.log("Config file not found, creating default config at " + root.filePath);
                writeAdapter();
            }
        }

        adapter: JsonAdapter {
            id: configJson

            property string fontFamily: "Google Sans"
            property int barStyle: 0 // 0 = edge, 1 = floating
            property int barPosition: 0 // 0 = top, 1 = bottom
            property int barCornerSize: 23
            property int persistentWorkspaceCount: 5
            property bool use24hrClock: false
            property bool batteryUseErrorContainer: true
            property real batteryLowThreshold: 0.2
            property bool btShowOnEmpty: true

            property list<string> taskbarPinnedApps: []
        }
    }

    property string fontFamily: "Google Sans" // Global font family for the whole shell.

    property string barStyle: "edge" // Style of the bar. Options: "edge", "floating"
    property string barPosition: "top" // Position of the bar. Options: "top", "bottom" (if the bar shows up in the middle of your screen, its not top or bottom)
    property int barHeight: 50 // Height of the bar in pixels (not everything fits well outside of 50 at the moment)
    property int barCornerSize: 23 // Size of the rounded corners on the bar (0 to disable)

    property bool spinAlbumArt: true // Whether to spin album art in the media player

    property int persistentWorkspaceCount: 5 // Number of persistent workspaces to show

    property bool use24hrClock: false // Whether to use 24 hour clock in the time display

    property bool batteryUseErrorContainer: true // Whether to use error container colors for low battery (less noticable) or just error colors (more noticable)
    property real batteryLowThreshold: 0.2 // Battery percentage threshold to consider battery as low (0.0 - 1.0)

    property bool btShowOnEmpty: true // Whether to show the Bluetooth icon when no devices are connected

}
